baseURL = "/"
languageCode = "zh-cn"
title = "个人技术空间"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true

[permalinks]
    post = "/p/:slug/"
    projects = "/projects/:slug/"
    learning = "/learning/:slug/"
    page = "/:slug/"

[pagination]
    pagerSize = 10

[taxonomies]
    tag = "tags"
    category = "categories"
