[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/"
    weight     = 1

[[main]]
    identifier = "posts"
    name       = "文章"
    url        = "/post/"
    weight     = 2

[[main]]
    identifier = "projects"
    name       = "项目"
    url        = "/projects/"
    weight     = 3

[[main]]
    identifier = "learning"
    name       = "学习"
    url        = "/learning/"
    weight     = 4

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"
    weight     = 5

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/about/"
    weight     = 6

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/<你的GitHub用户名>"
    weight     = 1

[[social]]
    identifier = "rss"
    name       = "RSS"
    url        = "/index.xml"
    weight     = 2
